### PR TITLE
Make repo branch for coverage diff configurable

### PR DESCRIPTION
**Pull request by SergK**
We can use some custom branch during code checkout, so let's
provide an ability for CI to redefine the branch

Env variable `COMPARE_BRANCH` can be used to re-define comparable branch

### CODE REVIEW

**Comment by marvin-tigera** [comment]
Can one of the admins verify this patch?

**Comment by marvin-tigera** [comment]
Can one of the admins verify this patch?

**Comment by marvin-tigera** [comment]
Can one of the admins verify this patch?

**Comment by fasaxc** [comment]
LGTM

**Pull request merged**
