### PR TITLE
Allow override of Typha and Hyperkube images in FVs

### PR DESCRIPTION
**Pull request by djlwilder**
To override hard-coded image names set environment variables:
K8_IMAGE and/or TYPHA_IMAGE.

Signed-off-by: David Wilder <wilder@us.ibm.com>

## Description
This PR works together with PR #1564 to select image names for functional verifications.  This is required to make fv arch agnostic.  The default image names are unchanged.
- which components are affected by this PR
-->  fv

## Todos
Set environment variables in the Makefile to override image names of non amd64 arch builds.  
Since this patch is not changing the default image names this patch is not dependent on the Makefile change.  I will submit a  separate PR for the Makefile change.

## Release Note
```release-note
None required
```

### CODE REVIEW

**Comment by fasaxc** [comment]
Unless I'm missing something, I think the code (using the `envconfig` library) you removed was _already_ loading environment variables for that purpose.  Is there a reason the existing code didn't work for ppc64?

**Comment by neiljerram** [comment]
Agreed, I'd prefer to keep EnvConfig  and meet the need by adding fields to the Config struct.

We need to merge #1596 first, then this PR could be reworked to do that.

**Comment by djlwilder** [comment]
Agreed,  I will test #1596 on ppc,  then do the rework on this PR.

**Comment by djlwilder** [comment]
Closing this PR,  continuing in PR#1599.

**Pull request closed without merging**
