### PR TITLE
Abolish BPF mode's fixed Calico mark pattern

### PR DESCRIPTION
**Pull request by neiljerram**

### CODE REVIEW

**Comment by tomastigera** [comment]
What is the rational? To free up a bit or two? (:+1: )

**Comment by neiljerram** [comment]
@tomastigera Yes, exactly.

**Comment by neiljerram** [comment]
@tomastigera
- Default IptablesMarkMask (0xFFFF0000) is 16 bits.
- BPF mode did use 11 bits (0x7FF00000)
- Because we use iptables for untracked egress policy, we need more of the iptables-mode bits, even in BPF mode
- And then Enterprise has various further bits that it tries to allocate for various features.

Net, we think it's really worthwhile to save the 2 Calico BPF fixed pattern bits now.

**Review by tomastigera — APPROVED** [review]
:cool:

**Pull request merged**
