### PR TITLE
Update libcalico-go to latest version

### PR DESCRIPTION
**Pull request by rikatz**
This PR updates libcalico-go to the latest version

Just to document the other changes were because of the following Kubernetes libraries changes:

* https://github.com/kubernetes/kubernetes/pull/96600 
   * OnlyNodeLocalEndpoints was renamed to NodeLocalExternal
   * New methods were added to ServicePorts interface which needed to be added here as well

* https://github.com/kubernetes/kubernetes/pull/99522 
  * adds a new method to ServicePorts (HintsAnnotation) which needed to be mapped

* https://github.com/kubernetes/kubernetes/pull/96440
  * discovery.AddressTypeIP was renamed to discovery.AddressTypeIPv4

### CODE REVIEW

**Comment by marvin-tigera** [comment]
Removing "merge-when-ready" label due to new commits

**Comment by fasaxc** [comment]
Thanks @rikatz.  Looks like the FVs have failed due to a known issue that will be fixed by #2755 ; hopefully we'll get that fixed in the next day or so and then your change can be rebased on top of the fix.

**Review by tomastigera — APPROVED** [review]
LGTM, thanks

**Comment by caseydavenport** [comment]
@rikatz it seems that you and @sridhartigera have reached a bit of a stalemate, where each PR is waiting on the other's!

I'm going to merge this and the @sridhartigera can rebase on top to finish off.

**Pull request merged**
