### PR TITLE
[WiP] Port "brains" of Felix to golang

### PR DESCRIPTION
**Pull request by fasaxc**
- Golang process becomes the main calico-felix process.
- Python code now becomes the "iptables dataplane driver".
- Golang process handles access to etcd via libcalico, paving the way for etdv3 support as well as other datastores.
- IP sets calculation moved to the golang process.
- New protobuf API between the Golang process and the Python process.
- New build process based on wrapping up pyinstaller bundles in the debs and RPMs.  Allows us to include the golang binary as well as vendoring all our dependencies, including Python itself.

### CODE REVIEW

**Comment by fasaxc** [comment]
retest this please

**Comment by marvin-tigera** [comment]
Build finished.

**Comment by marvin-tigera** [comment]
Build finished.

**Comment by marvin-tigera** [comment]
Build finished.

**Comment by marvin-tigera** [comment]
Build finished.

**Comment by marvin-tigera** [comment]
Build Failure
 No test results found.
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by fasaxc** [comment]
retest this please

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by marvin-tigera** [comment]
Test FAILed.

**Comment by fasaxc** [comment]
retest this please

**Comment by fasaxc** [comment]
retest this please

**Comment by fasaxc** [comment]
retest this please

**Comment by fasaxc** [comment]
retest this please

**Comment by fasaxc** [comment]
retest this please

**Comment by fasaxc** [comment]
retest this please

**Comment by fasaxc** [comment]
retest this please

**Comment by fasaxc** [comment]
retest this please

**Comment by fasaxc** [comment]
retest this please

**Comment by lwr20** [comment]
retest this please

**Comment by lwr20** [comment]
retest this please

**Comment by lwr20** [comment]
retest this please

**Comment by lwr20** [comment]
retest this please

**Pull request merged**
