### PR TITLE
Have usage reporting thread drain stats channel during startup delay

### LINKED ISSUE #1229: "Stats channel blocked" log spam at high scale
Initial sleep in usage reporting loop means that no-one is listening on the stats report channel. Each stats report before the initial timer pops then triggers a warning:

```
2016-12-10 00:55:10.851 [WARNING][99] stats_collector.go 127: Failed to report stats error=Stats channel blocked
```

### PR DESCRIPTION
**Pull request by fasaxc**
Fixes #1229

### CODE REVIEW

**Comment by fasaxc** [comment]
Tested locally and it seems to work as expected:
```
# bin/calico-felix | grep usagerep
2016-12-10 11:13:41.424 [INFO][10844] usagerep.go 36: Usage reporting thread started, waiting for size estimate
2016-12-10 11:13:41.440 [INFO][10844] usagerep.go 38: Initial stats read stats=calc.StatsUpdate{NumHosts:1, NumWorkloadEndpoints:1, NumHostEndpoints:0}
2016-12-10 11:13:41.440 [INFO][10844] usagerep.go 42: Waiting before first check-in delay=5m0.887s
2016-12-10 11:18:42.327 [INFO][10844] usagerep.go 60: Initial delay complete, making first check-in
2016-12-10 11:18:42.328 [INFO][10844] usagerep.go 126: Reporting cluster usage/checking for deprecation warnings. clusterGUID=baddecaf clusterType=unknown gitRevision=eaf4bde4d9e2f73eca7ff320116c63d055ce3d8b hostname=shauns-laptop stats=calc.StatsUpdate{NumHosts:1, NumWorkloadEndpoints:1, NumHostEndpoints:0} version=2.0.0-rc5
2016-12-10 11:18:43.534 [INFO][10844] usagerep.go 63: Initial check-in done, switching to timer. interval=24h0m0s
```

**Comment by fasaxc** [comment]
retest this please

**Comment by fasaxc** [comment]
@tomdee I'd like to get this into the next scale run, please can you review?

**Comment by tomdee** [comment]
Looks fine to me - but let's have a quick chat about it before you merge to make sure I understand it properly.

**Pull request merged**
