### PR TITLE
Fix except block in usage reporting to use full name of exception.

### LINKED ISSUE #1168: NameError: global name 'ResolutionError' is not defined
```
2016-11-08 01:08:24,232 [INFO][186/2] calico.felix.fetcd 594: etcd driver status changed to in-sync
2016-11-08 01:08:24,236 [ERROR][186/27] calico.felix.futils 502: Exception in wrapped function <function _periodically_usage_report at 0x7fc6b46455f0>
Traceback (most recent call last):
  File "site-packages/calico/felix/futils.py", line 500, in wrapped
  File "site-packages/calico/felix/fetcd.py", line 363, in _periodically_usage_report
NameError: global name 'ResolutionError' is not defined
Traceback (most recent call last):
  File "site-packages/gevent/greenlet.py", line 534, in run
  File "site-packages/calico/felix/futils.py", line 500, in wrapped
  File "site-packages/calico/felix/fetcd.py", line 363, in _periodically_usage_report
NameError: global name 'ResolutionError' is not defined
<Greenlet at 0x7fc6b3cde4b0: <bound method _FelixEtcdWatcher._periodically_usage_report of <_FelixEtcdWatcher at 0x7fc6b3cde410>>> failed with NameError
```

This is on `calico/node:v0.23.0`.

### PR DESCRIPTION
**Pull request by fasaxc**
Fixes #1168

### CODE REVIEW

**Comment by fasaxc** [comment]
@neiljerram I think this fixes the proximate cause of that issue but I'm not sure what the root cause was.

**Comment by neiljerram** [comment]
Oh, perhaps it's the exception traceback that is the next step there - in which case doubly fine.

**Comment by neiljerram** [comment]
retest this please

**Comment by neiljerram** [comment]
retest this please

**Comment by neiljerram** [comment]
Replaced by https://github.com/projectcalico/felix/pull/1183

**Pull request closed without merging**
