### PR TITLE
Allow to customize repo branch for coverage diff

### PR DESCRIPTION
**Pull request by SergK**
We can use some custom branch during code checkout, so let's
provide an ability for CI to redefine the branch, e.g.:

   make ut UT_COMPARE_BRANCH=gerrit/master

the default value is origin/master

### CODE REVIEW

**Comment by marvin-tigera** [comment]
Can one of the admins verify this patch?

**Comment by marvin-tigera** [comment]
Can one of the admins verify this patch?

**Comment by marvin-tigera** [comment]
Can one of the admins verify this patch?

**Comment by fasaxc** [comment]
ok to test

**Comment by fasaxc** [comment]
Nice idea, I'm not sure that diff-cover is working at the moment after all the rework but I don't see why this shouldn't go in anyway.

**Pull request merged**
