### PR TITLE
Use clang flag -target bpf

### PR DESCRIPTION
**Pull request by netoptimizer**
When compiling BPF code the clang flag `-target bpf` should be used.

The LLVM intermediate representation (IR) tries to stay architecture independent, but in some cases, when not using `-target bpf`, it can generate code (mostly data structure access) that will be rejected by the verifier.

This often happen if the program uses data structures with pointer or `long` / `unsigned long` types that interface with BPF helpers or context data structures.

More details see kernel Documentation:
https://www.kernel.org/doc/html/latest/bpf/bpf_devel_QA.html#q-clang-flag-for-target-bpf

I've only fixed this for the subdir "bpf-apache" as I had other compile issues in "bpf-gpl".
This the initial steps of moving towards using target bpf, the other places should of-cause also be fixed in follow ups.

### CODE REVIEW

**Comment by fasaxc** [comment]
@netoptimizer are you able to sign our CLA?  We can't accept contributions without it

**Comment by netoptimizer** [comment]
> @netoptimizer are you able to sign our CLA? We can't accept contributions without it

Sure. I've signed the CLA

**Comment by fasaxc** [comment]
Looks like the build fails when it's run inside our build container
```
mkdir -p .go-pkg-cache bin /home/semaphore/go/pkg/mod && docker run --rm --net=host --init -v /tmp/ssh-ryMYnoOxL2qp/agent.2559:/ssh-agent --env SSH_AUTH_SOCK=/ssh-agent -e GO111MODULE=on -v /home/semaphore/go/pkg/mod:/go/pkg/mod:rw -e LOCAL_USER_ID=1001 -e GOCACHE=/go-cache -e GOARCH=amd64 -e GOPATH=/go -e OS=linux -e GOOS=linux -e GOFLAGS="-mod=readonly" -v /home/semaphore/felix:/go/src/github.com/projectcalico/felix:rw -v /home/semaphore/felix/.go-pkg-cache:/go-cache:rw -w /go/src/github.com/projectcalico/felix calico/go-build:v0.40 sh -c "make -j -C bpf-apache all && \
--
1051 | make -j -C bpf-gpl all ut-objs"
1051 | Starting with UID : 1001
1053 | make: Entering directory '/go/src/github.com/projectcalico/felix/bpf-apache'
1053 | In file included from filter.c:15:
1055 | /usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
1055 | #include <asm/types.h>
1057 | ^~~~~~~~~~~~~
1057 | In file included from sockops.c:15:
1059 | In file included from /usr/include/linux/bpf.h:11:
1060 | /usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not foundIn file included from
1060 | redir.c:15:
1061 | In file included from /usr/include/linux/bpf.h:11:
1063 | /usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
1063 | #include <asm/types.h>
1064 | ^~~~~~~~~~~~~
1066 | #include <asm/types.h>
1066 | ^~~~~~~~~~~~~
1067 | 1 error generated.
1068 | 1 error generated.
1069 | 1 error generated.
1070 | make: *** [Makefile:53: redir.d] Error 1
1071 | make: *** Waiting for unfinished jobs....
1073 | make: *** [Makefile:53: filter.d] Error 1
1073 | make: *** [Makefile:53: sockops.d] Error 1
1075 | make: Leaving directory '/go/src/github.com/projectcalico/felix/bpf-apache'
1076 |  
1076 | make: *** [build-bpf] Error 2
```

**Comment by netoptimizer** [comment]
> 1053 | make: Entering directory '/go/src/github.com/projectcalico/felix/bpf-apache'
> 1053 | In file included from filter.c:15:
> 1055 | /usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
> 1055 | #include <asm/types.h>
> 1057 | ^~~~~~~~~~~~~
> 1057 | In file included from sockops.c:15:
> 1059 | In file included from /usr/include/linux/bpf.h:11:
> 1060 | /usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not found

I've seen this issue before on Ubuntu.

The solutions are either:

1) To have an extra include dir on Ubuntu (which seems too x86 specific):

```CFLAGS += -I/usr/include/x86_64-linux-gnu```

2) Or install the package `gcc-multilib` on Ubuntu (as desc i xdp-tutorial [setup_dependencies](https://github.com/xdp-project/xdp-tutorial/blob/master/setup_dependencies.org#packages-on-debianubuntu))

Not sure that you prefer?

**Comment by netoptimizer** [comment]
> The solutions are either:
> 
> 1. To have an extra include dir on Ubuntu (which seems too x86 specific):
> 
> `CFLAGS += -I/usr/include/x86_64-linux-gnu`
> 
> 2. Or install the package `gcc-multilib` on Ubuntu (as desc i xdp-tutorial [setup_dependencies](https://github.com/xdp-project/xdp-tutorial/blob/master/setup_dependencies.org#packages-on-debianubuntu))
> 

Asked upstream for their opinion: https://lore.kernel.org/bpf/20200729211341.1a713559@carbon/

I've currently chosen option-(1) the CFLAGS extra include search path. Mostly because this can be fixed in this git repo, as the package `gcc-multilib` option-(2) requires change to Dockerfile [projectcalico/go-build](https://github.com/projectcalico/go-build/blob/master/Dockerfile.amd64).

**Comment by fasaxc** [comment]
Ah, changing the compile mode has tweaked the binary and the UTs have a check on the BPF program tag.  I think that check is now bogus (we used to check in the compiled BPF program so we wanted to make sure that the checked in program was updated in lock step).  However, we no longer check in the programs so I don't think that check makes sense.  Feel free to remove the [check](https://github.com/projectcalico/felix/blob/master/bpf/bpf_test.go#L85), or just update the tags.

**Pull request merged**
