### PR TITLE
Packaging/docs: stop requiring /etc/calico/felix.cfg

### PR DESCRIPTION
**Pull request by neiljerram**

### CODE REVIEW

**Comment by neiljerram** [comment]
retest this please

**Comment by neiljerram** [comment]
retest this please

**Comment by fasaxc** [comment]
Changes look good.  Did you double-check that felix no longer needs the config file to exist?

**Comment by neiljerram** [comment]
retest this please

**Comment by neiljerram** [comment]
@fasaxc Yes - I noted that the PyInstaller / bare metal docs already said that /etc/calico/felix.cfg is optional.

**Comment by neiljerram** [comment]
retest this please

**Comment by neiljerram** [comment]
retest this please

**Comment by neiljerram** [comment]
retest this please

**Pull request merged**
