### PR TITLE
Add LogDebugFilenameRegex to control debug logging.

### PR DESCRIPTION
**Pull request by fasaxc**
## Description

Add a parameter that allows debug logs to be filtered by filename.

## Todos
- [ ] Unit tests (full coverage)
- [ ] Integration tests (delete as appropriate) In plan/Not needed/Done
- [ ] Documentation
- [ ] Backport
- [ ] Release note

## Release Note

```release-note
Felix now has a LogDebugFilenameRegex config parameter that allows debug logs to be filtered by filename.
```

### CODE REVIEW

**Review by neiljerram — APPROVED** [review]
LGTM modulo the temporary fasaxc pins.

Don't think I've seen an API change (FelixConfiguration) yet, but presumably that is coming?

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

**Comment by fasaxc** [comment]
Hit a flake on the first run then a quota issue on a different job.  Think that's good enough to go in.

**Pull request merged**
