### PR TITLE
Support for both appending and inserting chains in iptables dataplane

### PR DESCRIPTION
**Pull request by caseydavenport**
## Description

Goal of this PR is to enable both insertion and appending of iptables
chains (previously only one or the other was supported), to enable using 
that functionality (in a follow on PR) to make sure kube-proxy rules are hit even when policy
accepts the traffic by appending the accept rule after the kube-proxy
rules.

### CODE REVIEW

**Comment by neiljerram** [comment]
@song-jiang Per our discussion yesterday, I understood that you have already done this, so I wonder what this new PR is adding?

**Comment by fasaxc** [comment]
@neiljerram this PR is a cherry-pick of Song's work

**Comment by fasaxc** [comment]
I think you should bank this PR as a simple cherry-pick then follow up with the PR to fix services with no endpoints.

**Comment by caseydavenport** [comment]
Moved the fix for service rejection to a separate PR: https://github.com/projectcalico/felix/pull/2424

**Pull request merged**
