### PR TITLE
Update go-build version

### PR DESCRIPTION
**Pull request by caseydavenport**
I think this addresses the discovery in this PR: https://github.com/projectcalico/felix/pull/2045

Namely that we needed to update to a newer version of go-build. 

```
docker run -ti calico/go-build:v0.22 go version                
go version go1.12.6 linux/amd64

docker run -ti calico/go-build:v0.20 go version 
go version go1.11.2 linux/amd64

```

- [ ] Unit tests (full coverage)
- [ ] Integration tests (delete as appropriate) In plan/Not needed/Done
- [ ] Documentation
- [ ] Backport
- [ ] Release note

```release-note
None required
```

### CODE REVIEW

**Comment by neiljerram** [comment]
@caseydavenport Out of interest, though, re:
```
docker run -ti calico/go-build:v0.22 go version                
go version go1.12.6 linux/amd64

docker run -ti calico/go-build:v0.20 go version 
go version go1.11.2 linux/amd64
```
I was thinking it's the version of goimports that matters most here - is that right?  Is goimports included in the versioned golang distribution as shown here?

**Comment by caseydavenport** [comment]
@neiljerram yeah, good question. I assumed so because goimports doesn't seem to have a version reporting command AFAICT.

I also can't seem to see where we're pulling it in... it's not in our Dockerfile here: https://github.com/projectcalico/go-build/blob/master/Dockerfile.amd64

And, I don't see it in what appears to be the base image Dockerfile: https://github.com/docker-library/golang/blob/master/1.12/alpine3.9/Dockerfile

So, I guess I'm a little confused...

**Comment by neiljerram** [comment]
@caseydavenport Curious. But if it's working, I guess we don't need to worry.  Presumably one of the other Dockerfile steps pulls it in.  (Guess `gometalinter --install`?)

**Comment by caseydavenport** [comment]
>  But if it's working, I guess we don't need to worry.

Perhaps, though I've realized now that the packr file that was originally the problem no longer exists :D

**Pull request merged**
