### PR TITLE
Configure an option to append or insert the iptables rules generated

### PR DESCRIPTION
**Pull request by wmuizelaar**
Configure an option to append or insert the iptables rules generated
by calico-felix.

This helps to solve https://github.com/projectcalico/felix/issues/1118

Change-Id: I7986a8a2fce17771d4c515239eacbf930820fb51

### CODE REVIEW

**Comment by marvin-tigera** [comment]
Can one of the admins verify this patch?

**Comment by fasaxc** [comment]
@lxpollitt This PR adds a new `ChainInsertMode` config setting to control whether Felix inserts or appends its top-level jump rules.  Are you happy with that addition to the datamodel?

**Comment by lxpollitt** [comment]
Yes, I'm happy with that.  (I'm assuming that it defaults to current
behavior, and is configurable at both global and per host scopes, in the
same way as other?)  The new option will need to be included in
http://docs.projectcalico.org/v2.0/usage/configuration/ too.

**Comment by fasaxc** [comment]
@wmuizelaar Looks like the Golang UTs are failing, please can you fix up?
```
•! Panic [0.001 seconds]
Async calculation graph state sequencing tests: [It] should handle: [ep1 local, policy, ep2 local, policy] in normal ordering 
/go/src/github.com/projectcalico/felix/go/felix/calc/calc_graph_fv_test.go:890

  Test Panicked
  &{0xc4200140f0 map[] 2016-12-06 14:02:12.896758473 +0000 UTC panic Failed to parse metadata for config param ChainInsertMode <nil>}
  /usr/local/go/src/runtime/panic.go:458

  Full Stack Trace
  	/usr/local/go/src/runtime/panic.go:458 +0x243
  github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus.Entry.log(0xc4200140f0, 0xc420284000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4214d2600, ...)
  	/go/src/github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus/entry.go:124 +0x423
  github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc4200141e0, 0xc4214d2688, 0x1, 0x1)
  	/go/src/github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus/entry.go:169 +0x124
  github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus.(*Entry).Panicf(0xc4200141e0, 0x157a378, 0x2c, 0xc4214d2938, 0x1, 0x1)
  	/go/src/github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus/entry.go:217 +0x101
  github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus.(*Logger).Panicf(0xc4200140f0, 0x157a378, 0x2c, 0xc4214d2938, 0x1, 0x1)
  	/go/src/github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus/logger.go:172 +0x86
  github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus.Panicf(0x157a378, 0x2c, 0xc4214d2938, 0x1, 0x1)
  	/go/src/github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus/exported.go:147 +0x5f
  github.com/projectcalico/felix/go/felix/config.loadParams()
  	github.com/projectcalico/felix/go/felix/config/_obj/config_params.go:380 +0x20d7
  github.com/projectcalico/felix/go/felix/config.New(0x0)
  	github.com/projectcalico/felix/go/felix/config/_obj/config_params.go:525 +0x34f
  github.com/projectcalico/felix/go/felix/calc_test.glob..func2.1()
  	/go/src/github.com/projectcalico/felix/go/felix/calc/calc_graph_fv_test.go:815 +0x56
  github.com/projectcalico/felix/go/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc420a6b2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/go/src/github.com/projectcalico/felix/go/felix/calc/calc_suite_test.go:31 +0x64
  testing.tRunner(0xc4200843c0, 0x162bbc8)
  	/usr/local/go/src/testing/testing.go:610 +0x81
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:646 +0x2ec
  
------------------------------
```

I think the issue is that `config:"oneof(insert,append);insert;non-zero;die-on-fail"` should be `config:"oneof(insert,append);insert;non-zero,die-on-fail"`

**Comment by fasaxc** [comment]
ok to test

**Comment by wmuizelaar** [comment]
looks like a test failed - but I can't see the details. Anything still needs to be changed?

**Comment by fasaxc** [comment]
Another intermittent failure on the FVs, but this one I'm more certain is a known FV issue.  I think this patch is good to go.

**Pull request merged**
