### PR TITLE
Disable checksum offload on the VXLAN tunnel for kernels <v5.7.

### PR DESCRIPTION
**Pull request by fasaxc**
## Description

The combination of iptables MASQUERADE --random-fully and such kernels results in broken checksum calculations.

Fixes https://github.com/projectcalico/calico/issues/3145

## Todos
- [x] Unit tests (full coverage)
- [x] Integration tests (delete as appropriate) In plan/Not needed/Done
- [ ] Documentation
- [ ] Backport
- [x] Release note

## Release Note

```release-note
Disable VXLAN tunnel checksum offload on kernels <v5.7.  Works around https://github.com/projectcalico/calico/issues/3145.
```

### CODE REVIEW

**Review by neiljerram — APPROVED** [review]
LGTM.

**Review by caseydavenport — COMMENTED** [review]
Nice!

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

**Comment by champtar** [comment]
This disable VXLAN offload for RHEL/CentOS 8.x that is supposed to be fixed, any plan to improve the detection ?

**Pull request merged**
