### PR TITLE
Strip the `v` from the version number when building debs

### PR DESCRIPTION
**Pull request by caseydavenport**
## Description

Allows us to use a `v` like other calico components in the `calico/felix` release, but when building the debs they seem to need to start with a number. 

## Todos
- [ ] Unit tests (full coverage)
- [ ] Integration tests (delete as appropriate) In plan/Not needed/Done
- [ ] Documentation
- [ ] Backport
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
@fasaxc does this seem like the right thing to do more or less for allowing Felix to have version numbers starting with a `v` like everyone else?

**Comment by fasaxc** [comment]
Huh, I thought I saw another big Makefile PR go by overnight?  Was this included in that?

**Comment by caseydavenport** [comment]
@fasaxc just needed a rebase

**Comment by caseydavenport** [comment]
> What about when we release debs

hmmm. is this not the script that makes those debs? I had thought it was, but perhaps I'm missing something...

**Comment by fasaxc** [comment]
Re-reading the RELEASING doc, looks like it's changed and it _does_ rely on `make deb rpm`.

**Pull request merged**
