### PR TITLE
Hook SIGINT/TERM to shut down etcd watcher correctly.

### LINKED ISSUE #1076: etcd-driver sometimes takes a long time to die
Reported by @elfchief.  Sending a SIGTERM to felix sometimes leaves the etcd-driver running for a while.  We'd have better compatibility if we handled the SIGTERM and killed the etcd driver explicitly before exiting.

### PR DESCRIPTION
**Pull request by fasaxc**
Request from @elfchief to be a good citizen when we're sent a SIGTERM/INT.  This had also been annoying me a lot recently with the felix-backend work that I'd been doing.

Fixes #1076

### CODE REVIEW

**Comment by fasaxc** [comment]
retest this please

**Comment by lwr20** [comment]
retest this please

**Comment by lwr20** [comment]
retest this please

**Comment by lwr20** [comment]
retest this please

**Comment by lwr20** [comment]
retest this please

**Comment by lwr20** [comment]
retest this please

**Comment by lwr20** [comment]
retest this please

**Comment by lwr20** [comment]
retest this please

**Comment by fasaxc** [comment]
Closing this because I don't think it'll make it in before #1102, which resolves it in a different way.

**Pull request closed without merging**
