### PR TITLE
Build the felix RPMS on EL6 as well

### PR DESCRIPTION
**Pull request by wmuizelaar**
This PR allows the rpms to be also build on EL6.

### CODE REVIEW

**Comment by marvin-tigera** [comment]
Can one of the admins verify this patch?

**Comment by fasaxc** [comment]
ok to test

**Comment by fasaxc** [comment]
@wmuizelaar This might have broken the RH7 build: 
```
utils/make-packages.sh rpm
+++ realpath utils/make-packages.sh
++ dirname /home/jenkins/workspace/pull-request-build@2/build/utils/make-packages.sh
+ scriptdir=/home/jenkins/workspace/pull-request-build@2/build/utils
+ . /home/jenkins/workspace/pull-request-build@2/build/utils/lib.sh
++ git_repo_root
++ git rev-parse --show-toplevel
+ cd /home/jenkins/workspace/pull-request-build@2/build
++ git_auto_version
+++ git_last_tag
+++ git describe --tags --abbrev=0
++ last_tag=2.1.0-rc2
+++ git cherry -v 2.1.0-rc2
+++ wc -l
++ commits_since=2
+++ git_commit_id
+++ cut -c-7
+++ git rev-parse HEAD
++ sha=db26324
+++ date -u +%Y%m%d%H%M%S+0000
++ timestamp=20170206140921+0000
++ test 2 -eq 0
++ version=2.1.0-rc2.post2+20170206140921+0000+db26324
++ echo 2.1.0-rc2.post2+20170206140921+0000+db26324
+ version=2.1.0-rc2.post2+20170206140921+0000+db26324
++ git_commit_id
++ git rev-parse HEAD
++ cut -c-7
+ sha=db26324
++ id -u
+ MY_UID=1013
++ id -g
+ MY_GID=1013
++ pwd
+ DOCKER_RUN_RM='docker run --rm --user 1013:1013 -v /home/jenkins/workspace/pull-request-build@2/build:/code'
+ release=true
+ case ${version} in
+ release=false
+ for package_type in '"$@"'
+ case ${package_type} in
++ git_version_to_rpm 2.1.0-rc2.post2+20170206140921+0000+db26324
++ sed 's/\([0-9]\)-\?\(a\|b\|rc\|pre\)/\1_\2/'
++ echo 2.1.0-rc2.post2+20170206140921+0000+db26324
+ debver=2.1.0_rc2.post2+20170206140921+0000+db26324
+ rpm_spec=rpm/felix.spec
++ awk '/Felix ([^ ]+) \(from Git/{print $3;exit;}' rpm/felix.spec
+ last_pkgd_tag=2.0.2
++ git_tags_back_to 2.0.2
++ backstop_tag=2.0.2
++ cursor=HEAD
++ num_tags=0
++ '[' 0 -lt 10 ']'
+++ git describe --tags --abbrev=0 HEAD
++ previous_tag=2.1.0-rc2
++ '[' 2.1.0-rc2 = 2.0.2 ']'
++ echo 2.1.0-rc2
++ let 'num_tags += 1'
++ cursor='2.1.0-rc2^'
++ '[' 1 -lt 10 ']'
+++ git describe --tags --abbrev=0 '2.1.0-rc2^'
++ previous_tag=2.1.0-rc1
++ '[' 2.1.0-rc1 = 2.0.2 ']'
++ echo 2.1.0-rc1
++ let 'num_tags += 1'
++ cursor='2.1.0-rc1^'
++ '[' 2 -lt 10 ']'
+++ git describe --tags --abbrev=0 '2.1.0-rc1^'
++ previous_tag=2.0.2
++ '[' 2.0.2 = 2.0.2 ']'
++ break
+ tags='2.1.0-rc2
2.1.0-rc1'
+ IFS=_
+ read ver qual
+ test rc2.post2+20170206140921+0000+db26324
+ rpmver=2.1.0
+ rpmrel=0.1.rc2.post2+20170206140921+0000+db26324
+ sed -i 's/^Version:.*$/Version:        2.1.0/' rpm/felix.spec
+ sed -i 's/^Release:.*$/Release:        0.1.rc2.post2+20170206140921+0000+db26324%{?dist}/' rpm/felix.spec
+ grep -F ' 2.1.0-0.1.rc2.post2+20170206140921+0000+db26324' rpm/felix.spec
++ date '+%a %b %d %Y'
+ timestamp='Mon Feb 06 2017'
+ cat
+ sed -i '/^%changelog/ r /dev/stdin' rpm/felix.spec
+ false
+ cat
+ echo
+ for elversion in 7 6
+ docker run --rm --user 1013:1013 -v /home/jenkins/workspace/pull-request-build@2/build:/code -e EL_VERSION=el7 calico-build/centos7 rpm/build-rpms
+ set -e
+ '[' -z el7 ']'
+ repo=/code/
+ pkg=felix
+ mkdir -p /tmp/rpmbuild/BUILD /tmp/rpmbuild/RPMS /tmp/rpmbuild/SOURCES /tmp/rpmbuild/SPECS /tmp/rpmbuild/SRPMS
+ cd /tmp/rpmbuild
++ basename /code//rpm/felix.spec
+ spec=felix.spec
+ cd SPECS
+ cp -a /code//rpm/felix.spec .
++ grep Version: felix.spec
++ awk '{print $2;}'
+ version=2.1.0
+ cd ../SOURCES
+ for f in '${repo}/rpm/*'
+ ln -sf /code//rpm/build-rpms
+ for f in '${repo}/rpm/*'
+ ln -sf /code//rpm/calico-felix.init
+ for f in '${repo}/rpm/*'
+ ln -sf /code//rpm/calico-felix.logrotate
+ for f in '${repo}/rpm/*'
+ ln -sf /code//rpm/calico-felix.service
+ for f in '${repo}/rpm/*'
+ ln -sf /code//rpm/felix.spec
+ dir=felix-2.1.0
+ unpacked_src_dir=/tmp/felix-2.1.0
+ mkdir -p /tmp/felix-2.1.0/bin
+ cd /code/
+ cp bin/calico-felix /tmp/felix-2.1.0/bin
+ cp etc/calico-diags /tmp/felix-2.1.0/bin
+ cp etc/calico-gen-bird-conf.sh etc/calico-gen-bird-mesh-conf.sh etc/calico-gen-bird6-conf.sh etc/calico-gen-bird6-mesh-conf.sh /tmp/felix-2.1.0/bin
+ cp -r etc LICENSE README.md /tmp/felix-2.1.0
+ cd /tmp
+ tar -czf /tmp/rpmbuild/SOURCES/felix-2.1.0.tar.gz felix-2.1.0
+ cd rpmbuild
++ pwd
+ rpmbuild --define '_topdir /tmp/rpmbuild' --define 'dist .el7' -ba SPECS/felix.spec
warning: bogus date in %changelog: Tue Aug 10 2015 Matt Dupre <matt@projectcalico.org> 0.29~rc1
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.WacHmn
+ umask 022
+ cd /tmp/rpmbuild/BUILD
+ cd /tmp/rpmbuild/BUILD
+ rm -rf felix-2.1.0
+ /usr/bin/gzip -dc /tmp/rpmbuild/SOURCES/felix-2.1.0.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd felix-2.1.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.wuEwEi
+ umask 022
+ cd /tmp/rpmbuild/BUILD
+ cd felix-2.1.0
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.Is71Wd
+ umask 022
+ cd /tmp/rpmbuild/BUILD
+ '[' /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64 '!=' / ']'
+ rm -rf /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64
++ dirname /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64
+ mkdir -p /tmp/rpmbuild/BUILDROOT
+ mkdir /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64
+ cd felix-2.1.0
+ rm -rf /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64
+ install -d /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64/usr/bin/
+ install -m 755 bin/calico-diags bin/calico-felix bin/calico-gen-bird-conf.sh bin/calico-gen-bird-mesh-conf.sh bin/calico-gen-bird6-conf.sh bin/calico-gen-bird6-mesh-conf.sh /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64/usr/bin/
+ install -d -m 755 /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64/usr/share/calico
+ install -d -m 755 /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64/etc
+ install -d -m 755 /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64/usr/lib/systemd/system
+ install -p -D -m 755 /tmp/rpmbuild/SOURCES/calico-felix.service /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64/usr/lib/systemd/system/calico-felix.service
+ install -d /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64/etc/calico
+ install etc/felix.cfg.example /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64/etc/calico
+ install -d /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64/usr/share/calico/bird
+ install etc/bird/calico-bird-peer.conf.template etc/bird/calico-bird.conf.template etc/bird/calico-bird6-peer.conf.template etc/bird/calico-bird6.conf.template /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64/usr/share/calico/bird
+ install -d /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64/usr/bin
+ install -m 755 etc/calico-gen-bird-conf.sh etc/calico-gen-bird-mesh-conf.sh etc/calico-gen-bird6-conf.sh etc/calico-gen-bird6-mesh-conf.sh /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64/usr/bin
+ install -d -m 755 /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64//etc/logrotate.d
+ install -m 644 /tmp/rpmbuild/SOURCES/calico-felix.logrotate /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64//etc/logrotate.d/calico-felix
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 /tmp/rpmbuild/BUILD/felix-2.1.0
extracting debug info from /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64/usr/bin/calico-felix
nm: /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64/usr/bin/calico-felix: No symbols
dwz: Too few files for multifile optimization
/usr/lib/rpm/sepdebugcrcfix: Updated 1 CRC32s, 0 CRC32s did match.
cpio: /go/src/github.com/projectcalico/felix: Cannot stat: No such file or directory
0 blocks
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: calico-common-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64
Provides: calico-common = 2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7 calico-common(x86-64) = 2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: /bin/bash
Processing files: calico-felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64
Provides: calico-felix = 2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7 calico-felix(x86-64) = 2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7
Requires(interp): /bin/sh /bin/sh /bin/sh
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires(post): /bin/sh
Requires(preun): /bin/sh
Requires(postun): /bin/sh
Processing files: felix-debuginfo-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64
Provides: felix-debuginfo = 2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7 felix-debuginfo(x86-64) = 2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7
Requires(rpmlib): rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1 rpmlib(CompressedFileNames) <= 3.0.4-1
Checking for unpackaged file(s): /usr/lib/rpm/check-files /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64
Wrote: /tmp/rpmbuild/SRPMS/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.src.rpm
Wrote: /tmp/rpmbuild/RPMS/x86_64/calico-common-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64.rpm
Wrote: /tmp/rpmbuild/RPMS/x86_64/calico-felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64.rpm
Wrote: /tmp/rpmbuild/RPMS/x86_64/felix-debuginfo-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.6q18Ul
+ umask 022
+ cd /tmp/rpmbuild/BUILD
+ cd felix-2.1.0
+ rm -rf /tmp/rpmbuild/BUILDROOT/felix-2.1.0-0.1.rc2.post2+20170206140921+0000+db26324.el7.x86_64
+ exit 0
+ rm -rf /code/dist/rpms/el7
+ cp -r /tmp/rpmbuild /code/dist/rpms/el7
cp: cannot create directory '/code/dist/rpms/el7': No such file or directory
make: *** [rpm] Error 1
Build step 'Execute shell' marked build as failure
Archiving artifacts
Recording test results
```

**Comment by wmuizelaar** [comment]
@fasaxc at my local build-machine it now works - but it looks like Jenkins is still failing?

**Comment by fasaxc** [comment]
I think that's the next step of our build that's failing, the jenkins script is trying to pick up the RPMs and copy them to a test repo but I think you've moved the files from where it was expecting to find them.

**Comment by wmuizelaar** [comment]
Ah yes, that's true. I created el6 and el7-dirs inside the rpms-dir. Can move those to toplevel as well (just like the trusty/xenial builds)

**Comment by fasaxc** [comment]
@wmuizelaar How about keeping the RH7 ones in the old place and adding an "el6-rpms" dir next to it; then we won't have to change half a dozen CI scripts to look in the new place...

**Comment by wmuizelaar** [comment]
@fasaxc sounds like a plan!

**Comment by fasaxc** [comment]
LGTM

**Pull request merged**
