### PR TITLE
Add plumbing for ipv4_nat (for floating IPs)

### LINKED ISSUE #1253: Floating IPs don't work with Felix 2.0
Specifically, when using Calico with OpenStack,

- floating IPs do work with Felix 1.4.6

- floating IPs do not work with the Felix from https://launchpad.net/~project-calico/+archive/ubuntu/calico-2.0, which is Felix 2.0.0.

### PR DESCRIPTION
**Pull request by neiljerram**
Fixes #1253

### CODE REVIEW

**Comment by neiljerram** [comment]
retest this please

**Comment by neiljerram** [comment]
retest this please

**Comment by fasaxc** [comment]
Just needs some UT; I think we have some table-driven tests for rule conversion, should make it fairly easy to add that.

**Comment by neiljerram** [comment]
Yes indeed.  Also I gave it a run through the OpenStack CI (http://logs.openstack.org/59/394459/7/check/gate-tempest-dsvm-networking-calico-nv/302dc65/), and it didn't make that work....  so possibly this change isn't yet enough to make floating IPs work, or possibly there are other things wrong in that CI; no idea yet about the detail there.

Probably next step should be for me to test the floating IP aspect manually in one of our own rigs - but that would need a bit of time that I probably shouldn't be spending yet.

**Comment by neiljerram** [comment]
As well as passing successfully through the checks linked above, I've also tested that we have floating IPs working when this version of Felix is used with OpenStack:
- manually, by spinning up a test rig and creating and testing a floating IP that targets a VM
- using the OpenStack CI (Tempest) at http://logs.openstack.org/59/394459/8/check/gate-tempest-dsvm-networking-calico-nv/3c85161/.

Upshot: I think this change is good to go.

**Comment by fasaxc** [comment]
LGTM.

**Pull request merged**
